name: deploy-book

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:


# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt
        conda install -c conda-forge eccodes
        python -m eccodes selfcheck

    # Build the book
    - name: Build the book
      run: |
        jupyter-book clean src/ --all
        jupyter-book build src/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src/_build/html